### ISSUE TITLE
Shouldn't this be sampled_strings?

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/fmatch#1]
https://github.com/BAAQMD/fmatch/blob/aa90fc917e00b21f53bb3269c8757c53ad36d9c6/vignettes/fmatch_performance.Rmd#L28

I was wondering why my tests were never terminating. I think it's because you're benchmarking all strings over all patterns. The line above this defines a new variable called `sampled_strings`. Did you mean to have that varible be the first parameter to `fmatch` in this line?

**Comment by dholstius** [comment]
Closed by f6874281510d88424fd8394248abdcc3870afa0a.
